# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d5b09b057869fdffdf4ca064d430df20044d83b757df4bfee4ae58bb0d55e3bc367c3f60bfda3d3fe6054453b40a5a10a2663e4ef1c42b30e3bba2964efd2c8

test:
  secret_key_base: 22facc951b9532cbd3178e03da0b29f7f279041a708068e4dc72ee109b5bf3f4643bdc215721199d613a50d6c41f71a2c9c1688211b1936b972b053bb64dccea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
